package interfaces;

import Tools.Outils;
import Tools.Pion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JOptionPane;

public class Cellule extends javax.swing.JPanel implements MouseMotionListener, MouseListener {
    
    public static int TAILLE_CELL = 21;    //------ La taille de cellule est 21
    private int idL = 0;                   //------ L'id de cellule selon la ligne
    private int idC =0;                    //------l'id de cellule selon la colonne
    private Pion pion;                   
    
    //-------- Constructeur -------------
    public Cellule(int idL,int idC) {
        initComponents();
        this.idL = idL;
        this.idC= idC;
    }
    
    
    //-------- Getter & Setter ----------
    public void setIdL(int idL) {
        this.idL = idL;
    }
    
    public int getIdL() {
        return this.idL;
    }
    
    public void setIdC(int idC) {
        this.idC = idC;
    }
    
    public int getIdC() {
        return this.idC;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setBackground(new java.awt.Color(215, 189, 226));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(245, 238, 248)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //------- Dessiner un pion ------------
    public void drawPion(Color color) {
        pion = new Pion(color);
        this.repaint();
    }

    
    //--------------------
    public void eraseCellule() {
        this.repaint();
    }
    
    //-------- paint ----------
    @Override
    public void paint(Graphics g) {
        
        Graphics2D g2d = (Graphics2D) g;
        super.paint(g2d);
        if(pion != null)
           pion.dessinerPion((Graphics2D) g);
        else
        {
            Pion epion = new Pion(new Color(215, 189, 226));
                 epion.dessinerPion((Graphics2D) g);
        }
    }
    
    /***************************************************************************
     * Si le joueur a cliquer sur une position deja remplie par un pion, il va 
     * afficher sur l'ecran un message qui indique l'existenece de ce pion deja 
     * sur le plateau, sinon on remplie la case par le pion
     **************************************************************************/
    @Override
    public void mouseClicked(MouseEvent e) {
        
        if(pion != null)
        {
            JOptionPane.showMessageDialog(this, "Il y a un pion déja  !");
            System.out.println("Il y a un pion déja  !");
        }
        else
        {
            pion = new Pion(Color.black);
            int x = e.getComponent().getY()/50;
            int y = e.getComponent().getX()/50;
            int tmp;
            int k = 0;
            for(int i = 0; i < 19; i++)
            {
            	int l=0;
                for(int j = 0; j < 19; j++)
                {
                    if(x == i && y == j)
                    {
                        Outils.isClicked = true;
                        Outils.moveIndexL=this.getIdL();
                        Outils.moveIndexC=this.getIdC();
                        break;
                    }
                    l++;
                    
                }

                k++;
               
            }
            this.repaint();
        }   
    }
    
    @Override
    public void mouseDragged(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
